

<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require './vendor/autoload.php';

$mail = new PHPMailer();


$mail->SMTPDebug = 2;
$mail->isSMTP();
$mail->Host       = 'smtp-mail.outlook.com';
$mail->SMTPAuth   = true;
$mail->Username   = 'telford_meeting_ph@astigp.com';
$mail->Password   = 'Meet19533';
$mail->SMTPSecure = 'tls';
$mail->Port       = 587;

$mail->setFrom('telford_meeting_ph@astigp.com', 'PRMS Emailer');
$mail->addAddress('emailsender422@gmail.com', 'Email Reciever');

// $mail->addAddress('ellen@example.com');               //Name is optional
// $mail->addCC('cc@example.com');
// $mail->addBCC('bcc@example.com');

//Attachments
// $mail->addAttachment('/var/tmp/file.tar.gz');         //Add attachments
// $mail->addAttachment('../dist/img/no-image-available.png', 'new.jpg');    //Optional name

$mail->isHTML(true);
$mail->Subject = 'needs your approval';
$mail->Body    = 'Purchase Request number: <b></b> needs your approval. </br></br>Please login to our Purchase Request Management System (PRMS) to approve or cancel this request.</br></br>Thank you and have a nice day.</br></br></br>This mail is autogenerated by the PRMS System. Please do not reply directly.';
$mail->AltBody = 'Body in plain text for non-HTML mail clients';
$mail->send();
